# REFERENCE
# https://github.com/marketplace/actions/action-for-semantic-release

name: Release and Publish

on:
  push:
    # branches: 
    # - 'main'
  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  GHCR_TOKEN: ${{ secrets.GH_FULL_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_FULL_TOKEN }

jobs:
  release:
    name: Check & Version for Release
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.cycjimmy_release.outputs.new_release_published }}
      previousVersion: ${{ steps.cycjimmy_release.outputs.last_release_version }}
      newVersion: ${{ steps.cycjimmy_release.outputs.new_release_version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Analyze Commits for Semantic Release
        id: cycjimmy_release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
  
  publish:
    needs: release
    name: Publish Image
    runs-on: ubuntu-latest
    if: needs.release.outputs.changed == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log Into Registry
        uses: docker/login-action@v2
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} 
          password: ${{ env.GHCR_TOKEN }}

      - name: Build and Publish Image
        uses: docker/build-push-action@v3
        with:
           context: .
           push: true
           tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest, ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:v${{ needs.release.outputs.newVersion }}
  
  deploy:
    needs: publish
    name: Deploy to prod
    runs-on: [self-hosted, liatrio-runners-sharedsvc]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

